name: Unit Tests with Junit

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                  java-version: "21"
                  distribution: "temurin"
                  cache: maven
            - name: Set up environment variables
              env:
                  ENVIRONMENT: test
              run: |
                  echo "ENVIRONMENT=$ENVIRONMENT" > $GITHUB_WORKSPACE/.env

            - name: Run unit tests
              run: mvn test
